DROP TABLE IF EXISTS banned_ip;
CREATE TABLE banned_ip(
   id_ip      INT GENERATED ALWAYS AS IDENTITY
  ,ip     VARCHAR(30) NOT NULL
  ,created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
	);
INSERT INTO banned_ip(ip) VALUES ('23.129.64.132'); 


DROP TABLE IF EXISTS currency_by_country;
CREATE TABLE currency_by_country(
   id_cur      INT GENERATED ALWAYS AS IDENTITY
  ,country     VARCHAR(44) NOT NULL
  ,country_code VARCHAR(4) NOT NULL
  ,currency    VARCHAR(39) NOT NULL
  ,code        VARCHAR(3) NOT NULL
	);
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('New Zealand','NZ','New Zealand Dollars','NZD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Cook Islands','CK','New Zealand Dollars','NZD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Niue','NU','New Zealand Dollars','NZD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Pitcairn','PN','New Zealand Dollars','NZD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Tokelau','TK','New Zealand Dollars','NZD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Australian','AU','Australian Dollars','AUD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Christmas Island','CX','Australian Dollars','AUD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Cocos (Keeling) Islands','CC','Australian Dollars','AUD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Heard and Mc Donald Islands','HM','Australian Dollars','AUD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Kiribati','KI','Australian Dollars','AUD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Nauru','NR','Australian Dollars','AUD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Norfolk Island','NF','Australian Dollars','AUD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Tuvalu','TV','Australian Dollars','AUD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('American Samoa','AS','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Andorra','AD','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Austria','AT','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Belgium','BE','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Finland','FI','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('France','FR','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('French Guiana','GF','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('French Southern Territories','TF','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Germany','DE','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Greece','GR','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Guadeloupe','GP','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Ireland','IE','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Italy','IT','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Luxembourg','LU','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Martinique','MQ','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Mayotte','YT','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Monaco','MC','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Netherlands','NL','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Portugal','PT','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Reunion','RE','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Samoa','WS','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('San Marino','SM','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Slovenia','SI','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Spain','ES','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Vatican City State (Holy See)','VA','Euros','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('South Georgia and the South Sandwich Islands','GS','Sterling','GBP');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('United Kingdom','GB','Sterling','GBP');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Jersey','JE','Sterling','GBP');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('British Indian Ocean Territory','IO','USD','USD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Guam','GU','USD','USD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Marshall Islands','MH','USD','USD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Micronesia Federated States of','FM','USD','USD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Northern Mariana Islands','MP','USD','USD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Palau','PW','USD','USD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Puerto Rico','PR','USD','USD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Turks and Caicos Islands','TC','USD','USD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('United States','US','USD','USD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('United States Minor Outlying Islands','UM','USD','USD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Virgin Islands (British)','VG','USD','USD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Virgin Islands (US)','VI','USD','USD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Hong Kong','HK','HKD','HKD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Canada','CA','Canadian Dollar','CAD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Japan','JP','Japanese Yen','JPY');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Afghanistan','AF','Afghani','AFN');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Albania','AL','Lek','ALL');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Algeria','DZ','Algerian Dinar','DZD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Anguilla','AI','East Caribbean Dollar','XCD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Antigua and Barbuda','AG','East Caribbean Dollar','XCD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Dominica','DM','East Caribbean Dollar','XCD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Grenada','GD','East Caribbean Dollar','XCD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Montserrat','MS','East Caribbean Dollar','XCD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Saint Kitts','KN','East Caribbean Dollar','XCD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Saint Lucia','LC','East Caribbean Dollar','XCD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Saint Vincent Grenadines','VC','East Caribbean Dollar','XCD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Argentina','AR','Peso','ARS');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Armenia','AM','Dram','AMD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Aruba','AW','Netherlands Antilles Guilder','ANG');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Netherlands Antilles','AN','Netherlands Antilles Guilder','ANG');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Azerbaijan','AZ','Manat','AZN');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Bahamas','BS','Bahamian Dollar','BSD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Bahrain','BH','Bahraini Dinar','BHD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Bangladesh','BD','Taka','BDT');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Barbados','BB','Barbadian Dollar','BBD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Belarus','BY','Belarus Ruble','BYR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Belize','BZ','Belizean Dollar','BZD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Benin','BJ','CFA Franc BCEAO','XOF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Burkina Faso','BF','CFA Franc BCEAO','XOF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Guinea-Bissau','GW','CFA Franc BCEAO','XOF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Ivory Coast','CI','CFA Franc BCEAO','XOF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Mali','ML','CFA Franc BCEAO','XOF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Niger','NE','CFA Franc BCEAO','XOF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Senegal','SN','CFA Franc BCEAO','XOF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Togo','TG','CFA Franc BCEAO','XOF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Bermuda','BM','Bermudian Dollar','BMD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Bhutan','BT','Indian Rupee','INR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('India','IN','Indian Rupee','INR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Bolivia','BO','Boliviano','BOB');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Botswana','BW','Pula','BWP');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Bouvet Island','BV','Norwegian Krone','NOK');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Norway','NO','Norwegian Krone','NOK');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Svalbard and Jan Mayen Islands','SJ','Norwegian Krone','NOK');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Brazil','BR','Brazil','BRL');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Brunei Darussalam','BN','Bruneian Dollar','BND');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Bulgaria','BG','Lev','BGN');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Burundi','BI','Burundi Franc','BIF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Cambodia','KH','Riel','KHR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Cameroon','CM','CFA Franc BEAC','XAF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Central African Republic','CF','CFA Franc BEAC','XAF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Chad','TD','CFA Franc BEAC','XAF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Congo Republic of the Democratic','CG','CFA Franc BEAC','XAF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Equatorial Guinea','GQ','CFA Franc BEAC','XAF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Gabon','GA','CFA Franc BEAC','XAF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Cape Verde','CV','Escudo','CVE');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Cayman Islands','KY','Caymanian Dollar','KYD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Chile','CL','Chilean Peso','CLP');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('China','CN','Yuan Renminbi','CNY');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Colombia','CO','Peso','COP');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Comoros','KM','Comoran Franc','KMF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Costa Rica','CR','Costa Rican Colon','CRC');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Croatia (Hrvatska)','HR','Croatian Dinar','HRK');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Cuba','CU','Cuban Peso','CUP');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Cyprus','CY','Cypriot Pound','CYP');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Czech Republic','CZ','Koruna','CZK');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Denmark','DK','Danish Krone','DKK');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Faroe Islands','FO','Danish Krone','DKK');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Greenland','GL','Danish Krone','DKK');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Djibouti','DJ','Djiboutian Franc','DJF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Dominican Republic','DO','Dominican Peso','DOP');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('East Timor','TP','Indonesian Rupiah','IDR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Indonesia','ID','Indonesian Rupiah','IDR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Ecuador','EC','Sucre','ECS');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Egypt','EG','Egyptian Pound','EGP');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('El Salvador','SV','Salvadoran Colon','SVC');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Eritrea','ER','Ethiopian Birr','ETB');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Ethiopia','ET','Ethiopian Birr','ETB');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Estonia','EE','Estonian Kroon','EEK');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Falkland Islands (Malvinas)','FK','Falkland Pound','FKP');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Fiji','FJ','Fijian Dollar','FJD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('French Polynesia','PF','CFP Franc','XPF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('New Caledonia','NC','CFP Franc','XPF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Wallis and Futuna Islands','WF','CFP Franc','XPF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Gambia','GM','Dalasi','GMD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Georgia','GE','Lari','GEL');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Gibraltar','GI','Gibraltar Pound','GIP');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Guatemala','GT','Quetzal','GTQ');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Guinea','GN','Guinean Franc','GNF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Guyana','GY','Guyanaese Dollar','GYD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Haiti','HT','Gourde','HTG');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Honduras','HN','Lempira','HNL');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Hungary','HU','Forint','HUF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Iceland','IS','Icelandic Krona','ISK');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Iran (Islamic Republic of)','IR','Iranian Rial','IRR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Iraq','IQ','Iraqi Dinar','IQD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Israel','IL','Shekel','ILS');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Jamaica','JM','Jamaican Dollar','JMD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Jordan','JO','Jordanian Dinar','JOD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Kazakhstan','KZ','Tenge','KZT');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Kenya','KE','Kenyan Shilling','KES');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Korea North','KP','Won','KPW');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Korea South','KR','Won','KRW');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Kuwait','KW','Kuwaiti Dinar','KWD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Kyrgyzstan','KG','Som','KGS');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Latvia','LV','Lat','LVL');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Lebanon','LB','Lebanese Pound','LBP');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Lesotho','LS','Loti','LSL');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Liberia','LR','Liberian Dollar','LRD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Libyan Arab Jamahiriya','LY','Libyan Dinar','LYD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Liechtenstein','LI','Swiss Franc','CHF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Switzerland','CH','Swiss Franc','CHF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Lithuania','LT','Lita','LTL');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Macau','MO','Pataca','MOP');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Macedonia','MK','Denar','MKD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Madagascar','MG','Malagasy Franc','MGA');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Malawi','MW','Malawian Kwacha','MWK');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Malaysia','MY','Ringgit','MYR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Maldives','MV','Rufiyaa','MVR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Malta','MT','Maltese Lira','MTL');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Mauritania','MR','Ouguiya','MRO');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Mauritius','MU','Mauritian Rupee','MUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Mexico','MX','Peso','MXN');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Moldova Republic of','MD','Leu','MDL');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Mongolia','MN','Tugrik','MNT');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Morocco','MA','Dirham','MAD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Western Sahara','EH','Dirham','MAD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Mozambique','MZ','Metical','MZN');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Myanmar','MM','Kyat','MMK');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Namibia','NA','Dollar','NAD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Nepal','NP','Nepalese Rupee','NPR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Nicaragua','NI','Cordoba Oro','NIO');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Nigeria','NG','Naira','NGN');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Oman','OM','Sul Rial','OMR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Pakistan','PK','Rupee','PKR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Panama','PA','Balboa','PAB');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Papua New Guinea','PG','Kina','PGK');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Paraguay','PY','Guarani','PYG');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Peru','PE','Nuevo Sol','PEN');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Philippines','PH','Peso','PHP');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Poland','PL','Zloty','PLN');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Qatar','QA','Rial','QAR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Romania','RO','Leu','RON');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Russian Federation','RU','Ruble','RUB');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Rwanda','RW','Rwanda Franc','RWF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Sao Tome and Principe','ST','Dobra','STD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Saudi Arabia','SA','Riyal','SAR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Seychelles','SC','Rupee','SCR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Sierra Leone','SL','Leone','SLL');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Singapore','SG','Dollar','SGD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Slovakia (Slovak Republic)','SK','Koruna','SKK');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Solomon Islands','SB','Solomon Islands Dollar','SBD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Somalia','SO','Shilling','SOS');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('South Africa','ZA','Rand','ZAR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Sri Lanka','LK','Rupee','LKR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Sudan','SD','Dinar','SDG');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Suriname','SR','Surinamese Guilder','SRD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Swaziland','SZ','Lilangeni','SZL');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Sweden','SE','Krona','SEK');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Syrian Arab Republic','SY','Syrian Pound','SYP');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Taiwan','TW','Dollar','TWD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Tajikistan','TJ','Tajikistan Ruble','TJS');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Tanzania','TZ','Shilling','TZS');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Thailand','TH','Baht','THB');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Tonga','TO','PaÕanga','TOP');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Trinidad and Tobago','TT','Trinidad and Tobago Dollar','TTD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Tunisia','TN','Tunisian Dinar','TND');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Turkey','TR','Lira','TRY');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Turkmenistan','TM','Manat','TMT');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Uganda','UG','Shilling','UGX');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Ukraine','UA','Hryvnia','UAH');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('United Arab Emirates','AE','Dirham','AED');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Uruguay','UY','Peso','UYU');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Uzbekistan','UZ','Som','UZS');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Vanuatu','VU','Vatu','VUV');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Venezuela','VE','Bolivar','VEF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Vietnam','VN','Dong','VND');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Yemen','YE','Rial','YER');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Zambia','ZM','Kwacha','ZMK');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Zimbabwe','ZW','Zimbabwe Dollar','ZWD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Aland Islands','AX','Euro','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Angola','AO','Angolan kwanza','AOA');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Antarctica','AQ','Antarctican dollar','AQD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Bosnia and Herzegovina','BA','Bosnia and Herzegovina convertible mark','BAM');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Congo (Kinshasa)','CD','Congolese Frank','CDF');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Ghana','GH','Ghana cedi','GHS');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Guernsey','GG','Guernsey pound','GGP');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Isle of Man','IM','Manx pound','GBP');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Laos','LA','Lao kip','LAK');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Montenegro','ME','Euro','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Palestinian Territory','PS','Jordanian dinar','JOD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Saint Barthelemy','BL','Euro','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Saint Helena','SH','Saint Helena pound','GBP');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Saint Martin (French part)','MF','Netherlands Antillean guilder','ANG');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Saint Pierre and Miquelon','PM','Euro','EUR');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('Serbia','RS','Serbian dinar','RSD');
INSERT INTO currency_by_country(country,country_code,currency,code) VALUES ('US Armed Forces','USAF','US Dollar','USD');